### ISSUE TITLE
Condition tiles are duplicating until game is reloaded.

### ISSUE THREAD

**Issue by Androxilogin** [Entoarox/StardewMods#15] opened 2017-01-21 09:14 UTC
Discovered with days of the week conditions.

**Comment by Entoarox** [comment] 2017-01-21 13:11
Please give more detailed explanation, as the current description does not give enough detail.

**Comment by Androxilogin** [comment] 2017-01-21 14:41
It's a bit hard to explain so I'll add a portion of the manifest. Basically I'll have tiles be lain on say, monday then another tile the next day. When tuesday comes along the previous tile is there as well and so on. If I exit the game and return the tiles that stacked up are no longer present and the logic is reset to carry on. 

http://pastebin.com/HJEjwUtM

**Comment by Entoarox** [comment] 2017-01-21 15:20
Ah, now I get what you mean! this is not a bug, this is intended behavior.
Tiles are applied when their condition matches, but they remain in place from that point, *until/unless another condition changes that*
So if you do not want that behavior, just have a remove statement that undoes the previously applied edit.

Remembering what tiles have been conditionally applied is not within the capabilities I have, since other SMAPI mods might mess around with tiles themselves.

**Comment by Entoarox** [comment] 2017-01-21 15:23
Closing this as non-applicable.

**Closed by Entoarox** 2017-01-21 15:23 UTC
Labels: info needed

**Comment by Androxilogin** [comment] 2017-01-21 15:39
Sorry! Good to know before I get too deep in this thing.
